service:
  name: /zj_humanoid/hand/gesture_switch/right
  description: 右手手势切换
  type: hand/Gesture
  demos: right_hand_gesture_switch.yaml
  note: "控制右手执行指定手势。支持的手势包括:RESET、ROCK、ONE、TWO、THREE、FOUR等,手势名称大小写不敏感"
