service:
  name: /zj_humanoid/hand/gesture_switch/right
  description: 右手手势切换
  type: hand/Gesture
  demos: right_hand_gesture_switch.yaml
  note: ""
  applicable_robot_models: [H1, rx, wa1, wa2]  # 适用机器人型号
