service:
  name: /zj_humanoid/upperlimb/movej_by_path/right_arm
  description: 右臂轨迹movej
  type: upperlimb/MoveJByPath
  demos: case1.yaml
  note: "关节空间下,右臂轨迹点路径运动"
  applicable_robot_models: [H1, rx, wa1, wa2]
