service:
  name: /zj_humanoid/manipulation/joint_space_trajectory_planner
  description: 关节空间轨迹规划
  type: manipulation/JointSpaceTrajPlan
  demos: data.yaml
  note: "节空间轨迹规划，输出关节轨迹，示教模式下记录各个关节数据，据此生成完整的执行轨迹"
