service:
  name: /zj_humanoid/upperlimb/movej/waist
  description: 腰部movej
  type: upperlimb/MoveJ
  demos:
  - waist_v_acc_case1.yaml
  - waist_t_case1.yaml
  note: "关节空间下,腰部点到点运动"
  applicable_robot_models: [H1, I2, WA1, WA2]
