service:
  name: /zj_humanoid/hand/joint_switch/right
  description: 调用右手关节控制服务
  type: hand/HandJoint
  demos:
  - right_hand_joint_reset.yaml
  - right_hand_set_gesture_two.yaml
  - right_hand_set_gesture_yeah.yaml
  note: "控制右手各关节运动到指定角度。关节角度数组顺序为[拇指弯曲,拇指摆动,食指弯曲,中指弯曲,无名指弯曲,小指弯曲],单位:弧度。关节角度会被限制在安全范围内"
