service:
  name: /zj_humanoid/upperlimb/movej/left_arm
  description: 左臂movej
  type: upperlimb/MoveJ
  demos:
  - left_arm_v_acc_case1.yaml
  - left_arm_t_case1.yaml
  note: "关节空间下,左臂点到点运动"
  applicable_robot_models: [H1, I2, WA1, WA2]
