service:
  name: /zj_humanoid/hand/gesture_switch/left
  description: 左手手势切换
  type: hand/Gesture
  demos: left_hand_gesture_switch.yaml
  note: ""
  applicable_robot_models: [H1, rx, wa1, wa2]  # 适用机器人型号
