service:
  name: /zj_humanoid/upperlimb/movej_by_pose/dual_arm
  description: 双臂末端movej
  type: upperlimb/MoveJByPose
  demos: case1.yaml
  note: "tcp末端空间下,双臂末端位姿movej"
  applicable_robot_models: [H1, rx, wa1, wa2]
