service:
  name: /zj_humanoid/manipulation/execute_pick_task
  description: 执行抓取服务
  type: manipulation/ExecutePickTask
  demos: data.yaml
  note: "输出物品名称执行抓取服务"
  applicable_robot_models: [H1, WA1]  # 适用机器人型号
