service:
  name: /zj_humanoid/manipulation/scene_update
  description: 场景更新
  type: manipulation/SceneUpdate
  demos: data.yaml
  note: "机器人场景更新,基于二维码，需要场景中有二维码，机器人抓取物品前的环境感知"
  applicable_robot_models: [H1, WA1]  # 适用机器人型号
