service:
  name: /zj_humanoid/upperlimb/movej/dual_arm
  description: 双臂movej
  type: upperlimb/MoveJ
  demos:
  - dual_arm_v_acc_case1.yaml
  - dual_arm_t_case1.yaml
  note: "关节空间下,双臂点到点运动"
  applicable_robot_models: [H1, rx, wa1, wa2]
