service:
  name: /zj_humanoid/manipulation/pose_space_trajectory_planner
  description: 末端轨迹规划
  type: manipulation/MotionPlan
  demos: data.yaml
  note: "末端空间轨迹规划，示教模式下记录各个末端执行器数据，据此生成完整的执行轨迹"
  applicable_robot_models: [H1, WA1]  # 适用机器人型号
