service:
  name: /zj_humanoid/upperlimb/movej_by_path/left_arm
  description: 左臂轨迹movej
  type: upperlimb/MoveJByPath
  demos: case1.yaml
  note: "关节空间下,左臂轨迹点路径运动"
  applicable_robot_models: [H1, I2, WA1, WA2]
