service:
  name: /zj_humanoid/manipulation/pose_estimation_service
  description: 获取目标位姿
  type: manipulation/PoseEst
  demos: data.yaml
  note: "输入图像获取指定物品的6D位姿"
  applicable_robot_models: [H1, WA1]  # 适用机器人型号
