service:
  name: /zj_humanoid/upperlimb/movej/neck
  description: 脖子movej
  type: upperlimb/MoveJ
  demos:
  - neck_v_acc_case1.yaml
  - neck_t_case1.yaml
  note: "关节空间下,脖子点到点运动"
  applicable_robot_models: [H1, rx, wa1, wa2]
