service:
  name: /zj_humanoid/upperlimb/movej_by_pose/left_arm
  description: 左臂末端movej
  type: upperlimb/MoveJByPose
  demos: case1.yaml
  note: "tcp末端空间下,左臂末端位姿movej"
  applicable_robot_models: [H1, rx, wa1, wa2]
