project:
  description: 'ZJ Humanoid ROS1 APIs'
  version: "v1.0.0"

# 功能模块列表
modules:
  - audio
  - hand
  - lowerlimb
  - manipulation
  - navigation
  - robot
  - sensor
    - CAM_A
    - CAM_B
    - CAM_C
    - CAM_D
    - head_imu
    - realsense_down
    - realsense_up
    - realsense_head
  - upperlimb

# 机器人型号及其对应的功能模块排除列表
robot_models:
  U1:
    exclude_modules:
      - navigation
      - lowerlimb
      - sensor/realsense_down
      - sensor/realsense_head
  I2:
    exclude_modules:
      - manipulation
      - sensor/realsense_down
      - sensor/realsense_head
  WA1:
    exclude_modules:
      - lowerlimb
      - sensor/CAM_A
      - sensor/CAM_B
      - sensor/CAM_C
      - sensor/CAM_D
      - sensor/head_imu
      - sensor/realsense_down
      - manipulation
      - hand/task_switch
      - hand/wrist_force_sensor
      - navigation/version

  WA2:
    exclude_modules:
      - manipulation
      - lowerlimb
      - sensor/CAM_A
      - sensor/CAM_B
      - sensor/CAM_C
      - sensor/CAM_D
      - sensor/head_imu
      - sensor/realsense_down
      - upperlimb/movej/lift
      - upperlimb/go_home/lifting
      - upperlimb/movej_by_pose
      - upperlimb/movel
      - upperlimb/servol
      - upperlimb/speedl
      - upperlimb/speedj/lift
      - hand/task_switch
      - hand/wrist_force_sensor
