project:
  description: 'ZJ Humanoid ROS1 APIs'
  version: "v1.0.0"

# 功能模块列表
modules:
  - audio
  - hand
  - lowerlimb
  - manipulation
  - navigation
  - robot
  - sensor
  - upperlimb

# 机器人型号及其对应的功能模块排除列表
robot_models:
  H1:
    exclude_modules: []
  I2:
    exclude_modules: [navigation]  # I2型号不支持导航功能
  WA1:
    exclude_modules: []  
  WA2:
    exclude_modules: [manipulation]  # WA2型号不支持操作功能
