service:
  name: /zj_humanoid/upperlimb/movej_by_pose/right_arm
  description: 右臂末端movej
  type: upperlimb/MoveJByPose
  demos: case1.yaml
  note: "tcp末端空间下,右臂末端位姿movej"
  applicable_robot_models: [H1, I2, WA1, WA2]
