service:
  name: /zj_humanoid/audio/speaker/get_devices_list
  description: 获取播放设备
  type: audio/GetDeviceList
  note: "检查当前有多少个喇叭设备 回复数量应大于1"
  applicable_robot_models: [H1, I2, WA1, WA2]  # 适用机器人型号
