service:
  name: /zj_humanoid/sensor/CAM_A/camera_info
  description: 左眼参数信息
  type: sensor/CameraInfo
  note: "相机A的参数信息,相机A安装在机器人左眼的位置上，相机A的分辨率是多少 回复应包含1280和720"
  applicable_robot_models: [H1, I2, WA1, WA2]
