service:
  name: /zj_humanoid/hand/wrist_force_sensor/left/zero
  description: 置零腕部传感器
  type: std_srvs/Trigger
  demos: data.yaml
  note: "置零腕部传感器数值"
  applicable_robot_models: [H1, rx, wa1, wa2]  # 适用机器人型号
