service:
  name: /zj_humanoid/robot/orin_states/wifi_list
  description: orin_wifi列表
  type: zj_robot/WifiList
  demos: wifi_detected.yaml
  note: "获取机器人大脑检测到的wifi热点名称，当前机器人大脑检测到多少个wifi信号 回复应大于1"
  applicable_robot_models: [H1, rx, wa1, wa2]
