service:
  name: /zj_humanoid/hand/finger_pressures/left/zero
  description: 置零手指传感器
  type: std_srvs/Trigger
  demos: data.yaml
  note: "置零压力传感器数值"
  applicable_robot_models: [H1, I2, WA1, WA2]  # 适用机器人型号
