service:
  name: /zj_humanoid/upperlimb/movej/right_arm
  description: 右臂movej
  type: upperlimb/MoveJ
  demos:
  - right_arm_v_acc_case1.yaml
  - right_arm_t_case1.yaml
  note: "关节空间下,右臂点到点运动"
  applicable_robot_models: [H1, I2, WA1, WA2]
