service:
  name: /zj_humanoid/upperlimb/movej/whole_body
  description: 全身movej
  type: upperlimb/MoveJ
  demos:
  - whole_body_v_acc_case1.yaml
  - whole_body_t_case1.yaml
  note: "关节空间下,全身各部位点到点运动"
  applicable_robot_models: [H1, rx, wa1, wa2]
